-- V6__seed_schedule.sql
-- 8 week summary rows, then 56 daily schedule rows (8 × 7).
-- Columns: week_num, theme, focus_java, focus_dsa, focus_project

INSERT INTO schedule_weeks (week_num, theme, focus_java, focus_dsa, focus_project) VALUES
(1, 'Java Core Deep Dive',
   'Collections, OOP, Streams & Lambdas, Exception Handling, Concurrency, Java 17 features',
   'Arrays & Hashing, Two Pointers, Sliding Window, Binary Search',
   'Lesson seed data, unit tests, MockMvc controller tests'),
(2, 'Spring Boot Architecture',
   'DI & bean lifecycle, auto-configuration, @Transactional propagation, Spring profiles, Actuator',
   'Linked Lists, Trees (intro)',
   'Schedule API (V5+V6 migrations, ScheduleController, SchedulePage frontend)'),
(3, 'Data Access & Testing',
   'JPA entities & relationships, lazy vs eager, JPQL & @Query, Flyway evolution, Mockito patterns, @WebMvcTest',
   'Trees: BFS & DFS, Heaps, Binary Search',
   'Add @SpringBootTest round-trip tests, @DataJpaTest, refine LessonRepository'),
(4, 'Security & API Design',
   'Spring Security FilterChain, JWT structure & validation, JwtAuthFilter, CORS, REST best practices, pagination',
   'Graphs: BFS/DFS/Union-Find',
   'Spring Security config, JwtUtil, /api/auth/login stub, X-Total-Count header on lessons'),
(5, 'React Fundamentals',
   'Spring Boot review + behavioral prep (15 Q&A each)',
   'Heaps, 1-D Dynamic Programming',
   'React Error Boundary, useParams lesson route, AppContext for auth, Axios auth interceptor'),
(6, 'React Advanced + Performance',
   'Spring Boot microservices concepts for interview, behavioral stories',
   '2-D Dynamic Programming, Greedy, Intervals',
   'React.memo on LessonCard, React.lazy + Suspense code splitting, Vitest + RTL test suite'),
(7, 'System Design + Behavioral',
   'System design: URL shortener, news feed, rate limiter, DB scaling, caching, microservices',
   'Tries, Backtracking, Advanced DP',
   'Architecture diagram, ARCHITECTURE.md, mock system design interview, STAR stories'),
(8, 'Mock Interviews & Review',
   'Full review: Java + Spring Boot + System Design — full loop simulation',
   'Mixed Blind 75 review: all patterns',
   'Swagger/OpenAPI, Lighthouse report, README.md, deploy to Railway/Render, tag v1.0');

-- schedule_days: 56 rows
-- Columns: week_num, day_num, day_label,
--          learning_topic, learning_desc, learning_resource,
--          dsa_pattern, dsa_problems,
--          project_task, is_milestone

INSERT INTO schedule_days (week_num, day_num, day_label, learning_topic, learning_desc, learning_resource, dsa_pattern, dsa_problems, project_task, is_milestone) VALUES

-- ── WEEK 1: Java Core Deep Dive ────────────────────────────────────────────
(1, 1, 'Mon',
 'Collections & Generics',
 'ArrayList vs LinkedList internals, HashMap bucket/load-factor, when generics prevent ClassCastException at compile time.',
 'https://www.baeldung.com/java-collections',
 'Arrays & Hashing',
 'Two Sum, Valid Anagram, Group Anagrams',
 'Add 10 lesson rows to V3 seed SQL covering REST_APIS and JPA_HIBERNATE categories.',
 false),

(1, 2, 'Tue',
 'OOP: Interfaces vs Abstract Classes',
 'When to choose interface over abstract, default methods since Java 8, Liskov substitution, why interviewers ask this every round.',
 'https://www.baeldung.com/java-interface-vs-abstract-class',
 'Two Pointers',
 'Valid Palindrome, Two Sum II, Container With Most Water',
 'Wire LessonDetailPanel: on card click fetch lesson by ID, render contentHtml via dangerouslySetInnerHTML.',
 false),

(1, 3, 'Wed',
 'Streams & Lambdas',
 'filter/map/collect pipelines, Optional.orElseThrow, method references, parallel stream pitfalls.',
 'https://www.baeldung.com/java-8-streams',
 'Sliding Window',
 'Best Time To Buy Stock, Longest Substring Without Repeating, Longest Repeating Character Replacement',
 'Wire PATCH /lessons/{id}/status button in LessonDetailPanel; optimistic local state update in useLessons.',
 false),

(1, 4, 'Thu',
 'Exception Handling Patterns',
 'Checked vs unchecked, custom exceptions extending RuntimeException, @RestControllerAdvice pattern, never swallow Exception.',
 'https://www.baeldung.com/java-exceptions',
 'Binary Search',
 'Binary Search, Search Insert Position, Find Minimum in Rotated Array',
 'Write unit tests for LessonServiceImpl (8 test cases with Mockito, matching LessonServiceImplTest pattern).',
 false),

(1, 5, 'Fri',
 'Concurrency: Threads & Executors',
 'Runnable vs Callable, ExecutorService lifecycle, volatile vs synchronized, CompletableFuture chains, race condition traps.',
 'https://www.baeldung.com/java-util-concurrent',
 'Sliding Window',
 'Minimum Window Substring, Permutation in String',
 'Write @WebMvcTest controller tests for LessonController (7 test cases, MockMvc + MockBean).',
 false),

(1, 6, 'Sat',
 'Java 17 Features',
 'Records (immutable DTOs), text blocks, sealed classes, pattern-matching instanceof — new syntax interviewers now expect.',
 'https://openjdk.org/projects/jdk/17/',
 'Arrays & Hashing',
 'Encode and Decode Strings, Longest Consecutive Sequence',
 'Add GlobalExceptionHandler test: verify 404 body shape for unknown lesson ID (jsonPath $.message).',
 false),

(1, 7, 'Sun',
 'Week 1 Review: Java Core',
 'Java Core self-quiz: 20 common interview questions — answer out loud without notes, note gaps.',
 'https://www.interviewbit.com/java-interview-questions/',
 'Review & Revise',
 'Re-implement Two Sum, Group Anagrams, Valid Palindrome from scratch (no looking up)',
 'Run mvn clean test — all green. git tag v0.1.',
 true),

-- ── WEEK 2: Spring Boot Architecture ──────────────────────────────────────
(2, 1, 'Mon',
 'Spring DI & Bean Lifecycle',
 '@Component vs @Service vs @Repository semantic difference, bean scopes (singleton default), constructor vs field injection WHY.',
 'https://www.baeldung.com/spring-dependency-injection',
 'Linked Lists',
 'Reverse Linked List, Merge Two Sorted Lists',
 'Add ScheduleWeek + ScheduleDay entities and V5/V6 migrations to the project.',
 false),

(2, 2, 'Tue',
 'Auto-configuration & Starter POMs',
 'How @SpringBootApplication triggers auto-config, spring.factories, @Conditional — demystify the magic.',
 'https://www.baeldung.com/spring-boot-autoconfiguration',
 'Linked Lists',
 'Reorder List, Remove Nth Node From End of List',
 'Add ScheduleWeekRepository + ScheduleDayRepository + ScheduleService interface.',
 false),

(2, 3, 'Wed',
 '@Transactional Deep Dive',
 'Propagation levels (REQUIRED vs REQUIRES_NEW), read-only optimization, why you put it only on the service layer, not the repository.',
 'https://www.baeldung.com/transaction-configuration-with-jpa-and-spring',
 'Trees',
 'Invert Binary Tree, Maximum Depth of Binary Tree',
 'Implement ScheduleServiceImpl + ScheduleController GET /api/v1/schedule/weeks and /weeks/{weekNum}.',
 false),

(2, 4, 'Thu',
 'Spring Profiles & Configuration',
 'application-{profile}.yml, @Profile, environment-specific beans — used in every real project, never hardcode secrets.',
 'https://www.baeldung.com/spring-profiles',
 'Trees',
 'Same Tree, Subtree of Another Tree',
 'Write ScheduleServiceImplTest (3 Mockito test cases). Run mvn test → RED, then implement → GREEN.',
 false),

(2, 5, 'Fri',
 'Spring Boot Actuator',
 '/actuator/health, /actuator/metrics, custom HealthIndicator — common in production fintech interviews.',
 'https://www.baeldung.com/spring-boot-actuators',
 'Trees',
 'Count Good Nodes in Binary Tree, Validate BST',
 'Write ScheduleControllerTest with @WebMvcTest (3 test cases). Build SchedulePage frontend skeleton.',
 false),

(2, 6, 'Sat',
 'Spring Boot Testing Strategy',
 '@SpringBootTest vs @WebMvcTest vs @DataJpaTest — which slice loads what context and why speed matters.',
 'https://www.baeldung.com/spring-boot-testing',
 'Trees',
 'Kth Smallest in BST, Lowest Common Ancestor of BST',
 'Wire WeekSelector + DailyTable into SchedulePage. Connect to useSchedule/useWeekDetail hooks.',
 false),

(2, 7, 'Sun',
 'Week 2 Review: Spring Boot',
 'Spring Boot Q&A: 15 questions on DI, @Transactional, profiles, Actuator — answer without notes.',
 'https://www.interviewbit.com/spring-boot-interview-questions/',
 'Review & Revise',
 'Re-implement Reverse Linked List and Validate BST from scratch',
 'mvn clean test → green. Smoke test GET /api/v1/schedule/weeks in browser. git tag v0.2.',
 true),

-- ── WEEK 3: Data Access & Testing ─────────────────────────────────────────
(3, 1, 'Mon',
 'JPA Entities & Relationships',
 '@OneToMany vs @ManyToOne, @JoinColumn, CascadeType options, @MapsId — why enterprise Java codebases are full of JPA.',
 'https://www.baeldung.com/hibernate-one-to-many',
 'Trees: Level-Order BFS',
 'Binary Tree Level Order Traversal, Binary Tree Right Side View',
 'Add @SpringBootTest round-trip test for LessonRepository: save + find + assert.',
 false),

(3, 2, 'Tue',
 'JPA: Lazy vs Eager & N+1 Problem',
 'LazyInitializationException root cause, FetchType.LAZY default, JOIN FETCH in JPQL, EntityGraph — the #1 JPA interview gotcha.',
 'https://www.baeldung.com/hibernate-lazy-eager-loading',
 'Trees: BFS',
 'Binary Tree Zigzag Level Order Traversal',
 'Add @DataJpaTest for LessonRepository: test findByCategoryOrderBySortOrderAsc returns sorted results.',
 false),

(3, 3, 'Wed',
 'JPQL & @Query',
 'JPQL vs native SQL, @Query(nativeQuery=true), @Param binding, Spring Data projections — interview-ready examples.',
 'https://www.baeldung.com/spring-data-jpa-query',
 'Heaps / Priority Queue',
 'Kth Largest Element in an Array, Last Stone Weight',
 'Add @Query to LessonRepository: count lessons per category. Expose as GET /api/v1/lessons/stats.',
 false),

(3, 4, 'Thu',
 'Flyway Schema Evolution',
 'Versioned vs repeatable migrations, repair, baseline, checksum validation — used in every production database.',
 'https://documentation.red-gate.com/flyway',
 'Heaps',
 'K Closest Points to Origin, Task Scheduler',
 'Add V7 migration: add tags VARCHAR(200) column to lessons. Update Lesson entity and LessonSummaryDto.',
 false),

(3, 5, 'Fri',
 'Mockito Patterns',
 '@Mock vs @Spy, thenReturn vs thenThrow, ArgumentCaptor, verify() call counts — the full Mockito toolkit.',
 'https://www.baeldung.com/mockito-annotations',
 'Heaps',
 'Find Median from Data Stream, Top K Frequent Elements',
 'Write SessionService unit tests using Mockito (match LessonServiceImplTest structure and naming convention).',
 false),

(3, 6, 'Sat',
 '@WebMvcTest Deep Dive',
 '@MockBean vs @Mock, MockMvc fluent API, jsonPath assertions, how @RestControllerAdvice is included in slice.',
 'https://www.baeldung.com/spring-boot-testing',
 'Binary Search',
 'Search a 2D Matrix, Eating Bananas, Search in Rotated Array II',
 'Write controller tests for existing SessionController (GET /api/v1/sessions, POST /api/v1/chat).',
 false),

(3, 7, 'Sun',
 'Week 3 Review: JPA & Testing',
 'JPA & Testing Q&A: lazy loading, N+1, Flyway, Mockito traps, @WebMvcTest vs @SpringBootTest.',
 'https://www.baeldung.com/hibernate-common-performance-problems-in-spring-applications',
 'Review & Revise',
 'Re-implement K Closest Points and Search Rotated Array from scratch',
 'mvn clean test → all green. git tag v0.3.',
 true),

-- ── WEEK 4: Security & API Design ─────────────────────────────────────────
(4, 1, 'Mon',
 'Spring Security Architecture',
 'SecurityFilterChain, FilterChainProxy, OncePerRequestFilter, AuthenticationManager flow — the mental model for interviews.',
 'https://www.baeldung.com/spring-security-architecture',
 'Graphs: Islands',
 'Number of Islands, Max Area of Island',
 'Add spring-boot-starter-security to pom.xml. Configure SecurityConfig permitting /api/v1/** for now.',
 false),

(4, 2, 'Tue',
 'JWT: Structure & Validation',
 'Header.payload.signature, HMAC-SHA256, jjwt library, why JWTs are stateless and why that matters in microservices.',
 'https://www.baeldung.com/java-json-web-tokens-jjwt',
 'Graphs',
 'Clone Graph, Pacific Atlantic Water Flow',
 'Add io.jsonwebtoken:jjwt-api to pom.xml. Implement JwtUtil: generateToken, validateToken, getUsernameFromToken.',
 false),

(4, 3, 'Wed',
 'JWT Filter in Spring Security',
 'Extend OncePerRequestFilter, extract Bearer token from Authorization header, set SecurityContextHolder.',
 'https://www.baeldung.com/spring-security-oauth-jwt',
 'Graphs',
 'Surrounded Regions, Rotting Oranges',
 'Add JwtAuthFilter. Add POST /api/auth/login endpoint returning hardcoded test token.',
 false),

(4, 4, 'Thu',
 'CORS & REST API Versioning',
 'CORS preflight, @CrossOrigin vs CorsConfigurationSource, URI versioning (/v1/) — already in project, understand WHY.',
 'https://www.baeldung.com/spring-cors',
 'Graphs: Topological Sort',
 'Course Schedule, Course Schedule II',
 'Update CorsConfig to explicitly allow http://localhost:5173. Add placeholder /api/v2/lessons redirect.',
 false),

(4, 5, 'Fri',
 'REST API Design Best Practices',
 'Idempotency (GET/PUT/DELETE), pagination headers (X-Total-Count), error bodies RFC 7807, HATEOAS basics.',
 'https://www.baeldung.com/rest-with-spring-series',
 'Graphs: Union-Find',
 'Number of Connected Components, Redundant Connection',
 'Add X-Total-Count response header to GET /api/v1/lessons. Add ?page=&size= pagination support.',
 false),

(4, 6, 'Sat',
 'OAuth2 Basics',
 'Authorization Code + PKCE flow, access vs refresh tokens, when to use OAuth2 vs simple JWT — interview staple.',
 'https://www.baeldung.com/spring-security-oauth',
 'Graphs',
 'Graph Valid Tree, Alien Dictionary',
 'Add Google OAuth2 login button to frontend (UI only, not wired to server — shows you know the flow).',
 false),

(4, 7, 'Sun',
 'Week 4 Review: Security',
 'Security Q&A: JWT, FilterChain, CORS, OAuth2 — answer without notes. Record yourself for 15 minutes.',
 'https://www.baeldung.com/security-spring',
 'Review & Revise',
 'Re-implement Number of Islands and Course Schedule from scratch',
 'mvn clean test → green. Manually test /api/auth/login returns JWT. git tag v0.4.',
 true),

-- ── WEEK 5: React Fundamentals ────────────────────────────────────────────
(5, 1, 'Mon',
 'useState & useEffect Deep Dive',
 'Closure traps with stale state, cleanup functions, why the deps array matters, render cycle — interviewers probe these.',
 'https://react.dev/reference/react/useState',
 '1-D Dynamic Programming',
 'Climbing Stairs, House Robber, Min Cost Climbing Stairs',
 'Refactor useLessons: replace cancelled flag with AbortController for proper fetch cancellation.',
 false),

(5, 2, 'Tue',
 'useCallback & useMemo — When NOT to Use',
 'Referential equality, when memo actually helps vs adds noise, premature optimization pitfalls.',
 'https://react.dev/reference/react/useCallback',
 '1-D DP',
 'Palindromic Substrings, Decode Ways, Coin Change',
 'Add React Error Boundary component. Wrap LessonsPage and SchedulePage in <ErrorBoundary>.',
 false),

(5, 3, 'Wed',
 'React Router v6: useParams, useNavigate, Outlet',
 'Nested routes, layout routes, dynamic segments, redirect patterns — v6 changed everything from v5.',
 'https://reactrouter.com/en/main/start/tutorial',
 '1-D DP',
 'Maximum Product Subarray, Word Break',
 'Add /lessons/:id route. Clicking a card navigates; LessonDetailPanel reads lesson ID from useParams.',
 false),

(5, 4, 'Thu',
 'React Context API',
 'createContext, useContext, Provider pattern — when Context beats prop drilling and when to reach for Zustand instead.',
 'https://react.dev/learn/passing-data-deeply-with-context',
 '1-D DP',
 'Longest Increasing Subsequence, Partition Equal Subset Sum',
 'Add AppContext: provides currentUser + setCurrentUser (mock user for now). Wrap App in AppProvider.',
 false),

(5, 5, 'Fri',
 'Compound Components & Render Props',
 'Flexible component APIs used in real component libraries — composition over inheritance pattern.',
 'https://www.patterns.dev/react/compound-pattern',
 '2-D DP',
 'Unique Paths, Longest Common Subsequence',
 'Refactor WeekSelector to accept an optional renderTab render prop for custom tab rendering.',
 false),

(5, 6, 'Sat',
 'Axios Interceptors & Error Normalization',
 'Request interceptors (attach Bearer token), response interceptors (normalize errors) — already partial in axios.js.',
 'https://axios-http.com/docs/interceptors',
 '2-D DP',
 'Best Time to Buy and Sell Stock with Cooldown',
 'Update axios.js request interceptor: read JWT from localStorage, attach as Authorization: Bearer <token>.',
 false),

(5, 7, 'Sun',
 'Week 5 Review: React Fundamentals',
 'React Hooks Q&A: 15 questions on useState, useEffect, Context, refs — answer without notes.',
 'https://react.dev/learn',
 'Review & Revise',
 'Re-implement Coin Change and Unique Paths from scratch',
 'npm test → green. git tag v0.5.',
 true),

-- ── WEEK 6: React Advanced + Performance ──────────────────────────────────
(6, 1, 'Mon',
 'React.memo & Memoization',
 'Referential equality, when React.memo prevents re-renders, common pitfall: objects/arrays as props break memo.',
 'https://react.dev/reference/react/memo',
 'Greedy',
 'Maximum Subarray, Jump Game, Jump Game II',
 'Wrap LessonCard in React.memo. Open React DevTools Profiler and compare render counts before/after.',
 false),

(6, 2, 'Tue',
 'React.lazy + Suspense Code Splitting',
 'Dynamic import(), Suspense fallback, route-level splitting to reduce initial bundle size.',
 'https://react.dev/reference/react/lazy',
 'Greedy',
 'Gas Station, Hand of Straights',
 'Lazy-load LessonsPage and SchedulePage. Add <Suspense fallback={<div>Loading...</div>}> in App.jsx.',
 false),

(6, 3, 'Wed',
 'Custom Hook Composition Patterns',
 'Extract data-fetching logic, combine multiple hooks cleanly, test hooks in isolation.',
 'https://react.dev/learn/reusing-logic-with-custom-hooks',
 'Intervals',
 'Insert Interval, Merge Intervals, Meeting Rooms',
 'Extract useWeekSelector hook from SchedulePage: manages selectedWeekNum state + prev/next helpers.',
 false),

(6, 4, 'Thu',
 'CSS: Design Tokens, Grid, Accessibility',
 'CSS custom properties as tokens (already in global.css), CSS Grid for table layouts, focus-visible, aria-label.',
 'https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout',
 'Intervals',
 'Minimum Interval to Include Each Query',
 'Improve DailyTable: switch from HTML table to CSS Grid. Add aria-label to each cell for accessibility.',
 false),

(6, 5, 'Fri',
 'Vite Config & Env Variables',
 'vite.config.js plugins, import.meta.env, .env.production vs .env.development, proxy for local backend.',
 'https://vitejs.dev/guide/env-and-mode',
 'Stack',
 'Valid Parentheses, Min Stack, Evaluate Reverse Polish Notation',
 'Add .env.production with VITE_API_BASE_URL pointing to deployed backend. Add dev proxy in vite.config.js.',
 false),

(6, 6, 'Sat',
 'Frontend Testing: Vitest + RTL',
 'vitest setup, @testing-library/react, userEvent, getByRole queries, async waitFor patterns.',
 'https://testing-library.com/docs/react-testing-library/intro',
 'Stack',
 'Generate Parentheses, Daily Temperatures',
 'Add vitest + @testing-library/react + jsdom. Write tests: WeekSelector renders 8 tabs, click activates correct week.',
 false),

(6, 7, 'Sun',
 'Week 6 Review: React Advanced',
 'React Performance Q&A: memo, lazy, Suspense, profiling — when does optimization actually help?',
 'https://react.dev/learn/render-and-commit',
 'Review & Revise',
 'Re-implement Jump Game and Merge Intervals from scratch',
 'npm run build → 0 errors. npm test → green. git tag v0.6.',
 true),

-- ── WEEK 7: System Design + Behavioral ────────────────────────────────────
(7, 1, 'Mon',
 'System Design: URL Shortener',
 'Unique ID generation (base62), 301 vs 302 redirect, caching layer, DB schema, rate limiting per user.',
 'https://www.educative.io/courses/grokking-the-system-design-interview',
 'Tries',
 'Implement Trie, Design Add and Search Words Data Structure',
 'Write 3 STAR behavioral stories: conflict resolution, tight deadline, and a technical tradeoff you made.',
 false),

(7, 2, 'Tue',
 'System Design: News Feed (Twitter/Instagram)',
 'Fanout-on-write vs fanout-on-read, pagination cursors, CDN for media, DB sharding by user_id.',
 'https://www.youtube.com/watch?v=hnpzNAPiC0E',
 'Tries',
 'Search Suggestions System',
 'Write 3 more STAR stories: mentoring a colleague, cross-team collaboration, production incident you resolved.',
 false),

(7, 3, 'Wed',
 'System Design: Rate Limiter',
 'Token bucket vs leaky bucket algorithms, Redis sorted sets for sliding window, distributed rate limiting.',
 'https://www.youtube.com/watch?v=FU4WlwfS3G0',
 'Backtracking',
 'Subsets, Combination Sum',
 'Conduct a 45-min mock system design interview (record yourself or use Pramp.com). Review recording.',
 false),

(7, 4, 'Thu',
 'System Design: Database Scaling',
 'Vertical vs horizontal scaling, read replicas, sharding strategies (range vs hash), consistent hashing.',
 'https://www.youtube.com/watch?v=vg86F0jUGdA',
 'Backtracking',
 'Permutations, Subsets II',
 'Record a 30-min mock behavioral interview out loud. Score yourself on STAR completeness.',
 false),

(7, 5, 'Fri',
 'System Design: Caching Strategies',
 'Redis data structures (String/Hash/ZSet), write-through vs write-behind, LRU/LFU eviction, cache stampede.',
 'https://www.youtube.com/watch?v=U3RkDLtS7uY',
 'Backtracking',
 'Word Search',
 'Add draw.io architecture diagram to project docs: frontend → Spring Boot → PostgreSQL with labels.',
 false),

(7, 6, 'Sat',
 'System Design: Microservices vs Monolith',
 'Service boundaries, API gateway, distributed transactions (saga pattern), when NOT to split — trade-offs.',
 'https://www.youtube.com/watch?v=rv4LlmLmVWk',
 'Graph Algorithms',
 'Alien Dictionary',
 'Write ARCHITECTURE.md: document layered architecture, design decisions, and what you would change at scale.',
 false),

(7, 7, 'Sun',
 'Week 7 Review: System Design',
 'System Design mock: design the Lessons app at 10M users. Practice solo for 45 min with no notes.',
 'https://github.com/donnemartin/system-design-primer',
 'Review & Revise',
 'Re-implement Combination Sum and Word Search from scratch',
 'Commit all docs and diagrams. git tag v0.7.',
 true),

-- ── WEEK 8: Mock Interviews & Review ──────────────────────────────────────
(8, 1, 'Mon',
 'Java Full Mock Interview (45 min)',
 'Java Core + Concurrency + OOP: answer without notes, time yourself, write down every gap for review.',
 'https://www.interviewbit.com/java-interview-questions/',
 'Mixed Review',
 'Two Sum, Valid Anagram, LRU Cache',
 'Fix any remaining test failures. Ensure mvn clean test → 100% green across all test classes.',
 false),

(8, 2, 'Tue',
 'Spring Boot Full Mock Interview (45 min)',
 'DI, @Transactional, security, JPA: whiteboard an API design from scratch. Record 15-min answer on @Transactional.',
 'https://www.interviewbit.com/spring-boot-interview-questions/',
 'Mixed Review',
 'Number of Islands, Course Schedule',
 'Add Swagger/OpenAPI 3 docs: springdoc-openapi-starter-webmvc-ui. Access at /swagger-ui.html.',
 false),

(8, 3, 'Wed',
 'React Full Mock Interview (45 min)',
 'Build a filterable list component from a mock API: useState, useEffect, fetch, error handling — timed.',
 'https://react.dev/learn',
 'Mixed Review',
 'Longest Palindromic Substring, Maximum Product Subarray',
 'Add Lighthouse performance report (npm run build → serve → Lighthouse). Document scores in README.',
 false),

(8, 4, 'Thu',
 'System Design Mock (60 min)',
 'Design the Interview Coach app at scale: 10M users, DB, caching, auth, CDN, rate limiting — solo.',
 'https://github.com/donnemartin/system-design-primer',
 'Mixed Review',
 'Find Minimum in Rotated Sorted Array, Search in Rotated Sorted Array',
 'Write project README.md: what it does, tech stack table, how to run locally, link to architecture diagram.',
 false),

(8, 5, 'Fri',
 'Behavioral Full Mock (30 min)',
 'Tell me about yourself, greatest challenge, conflict with a colleague, why this company — answer out loud, timed.',
 'https://www.themuse.com/advice/star-interview-method',
 'Mixed Review',
 'Sliding Window Maximum, Minimum Window Substring',
 'Deploy backend to Railway.app (free tier). Deploy frontend to Vercel. Verify prod URLs work end-to-end.',
 false),

(8, 6, 'Sat',
 'Full Loop Simulation (4 hours)',
 'Simulate a full interview day: 2 coding rounds (45 min each) + 1 system design (60 min) + 1 behavioral (30 min).',
 'https://www.pramp.com/',
 'Mixed Review',
 'Serialize and Deserialize BST',
 'Final code review: no TODOs, no console.log in production code, no hardcoded secrets, all tests pass.',
 false),

(8, 7, 'Sun',
 'Rest & Light Review',
 'Review all cheat sheets: Java, Spring Boot, React, System Design one-pagers. Rest. You are ready.',
 'https://github.com/interviews/interview-cheat-sheet',
 'Light Review',
 'Review 3 problems you found hardest this week — read editorial, do not re-implement',
 'git tag v1.0. Update resume with project URL. Send applications.',
 true);
