spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: false
    hibernate:
      format_sql: false
  flyway:
    out-of-order: false

logging:
  level:
    root: INFO
    com.anthropic: DEBUG
